### ISSUE TITLE
Fotos de notas cuadradas 

### ISSUE THREAD

**Issue by codemax-dw** [UBV-P420/p420theme#2]
Ajustar visualmente según [presentación - diapositiva 4](https://docs.google.com/presentation/d/174z7t1_h5drxurcPCckFOBe7Z3cyVE_gasQ-w9V4DmA/edit?usp=sharing).

La sección completa se encuentra envuelta por la clase .p420-posts-grid.
Declarada en el archivo: /ui/front/scss/src/blocks/_posts-grid.scss.

**Comment by FlyingPumba** [comment]
@codemax-dw ahí creo que quedó arreglado en la versión que subí recién (`v0.6.7`)/
